### ISSUE TITLE
Unhandled Exception: Converting object to an encodable object failed: Instance of 'TweetExpansion'

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#288]
# 1. Current bug behavior

```bash
E/flutter ( 4986): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'TweetExpansion'
E/flutter ( 4986): #0      _JsonStringifier.writeObject (dart:convert/json.dart:794:7)
E/flutter ( 4986): #1      _JsonStringifier.writeList (dart:convert/json.dart:842:7)
E/flutter ( 4986): #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:824:7)
E/flutter ( 4986): #3      _JsonStringifier.writeObject (dart:convert/json.dart:785:9)
E/flutter ( 4986): #4      _JsonStringifier.writeMap (dart:convert/json.dart:875:7)
E/flutter ( 4986): #5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:830:21)
E/flutter ( 4986): #6      _JsonStringifier.writeObject (dart:convert/json.dart:785:9)
E/flutter ( 4986): #7      _JsonStringStringifier.printOn (dart:convert/json.dart:983:17)
E/flutter ( 4986): #8      _JsonStringStringifier.stringify (dart:convert/json.dart:968:5)
E/flutter ( 4986): #9      JsonEncoder.convert (dart:convert/json.dart:345:30)
E/flutter ( 4986): #10     JsonCodec.encode (dart:convert/json.dart:231:45)
E/flutter ( 4986): #11     jsonEncode (dart:convert/json.dart:114:10)
E/flutter ( 4986): #12     BaseService.post (package:twitter_api_v2/src/service/base_service.dart:131:13)
E/flutter ( 4986): #13     _TweetsService.createTweet (package:twitter_api_v2/src/service/tweets/tweets_service.dart:2212:21)
E/flutter ( 4986): #14     _TweetViewState.build.<anonymous closure> (package:example/src/tweet_view.dart:66:67)
E/flutter ( 4986): #15     _TweetViewState.build.<anonymous closure> (package:example/src/tweet_view.dart:65:30)
E/flutter ( 4986): #16     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
E/flutter ( 4986): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter ( 4986): #18     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
E/flutter ( 4986): #19     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
E/flutter ( 4986): #20     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)
E/flutter ( 4986): #21     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
E/flutter ( 4986): #22     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
E/flutter ( 4986): #23     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
E/flutter ( 4986): #24     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
E/flutter ( 4986): #25     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
E/flutter ( 4986): #26     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
E/flutter ( 4986): #27     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
E/flutter ( 4986): #28     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
E/flutter ( 4986): #29     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
E/flutter ( 4986): #30     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
E/flutter ( 4986): #31     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
E/flutter ( 4986): #32     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
E/flutter ( 4986): #33     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
E/flutter ( 4986): #34     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter ( 4986): #35     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4986): #36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4986): #37     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter ( 4986): #38     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter ( 4986): #39     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
E/flutter ( 4986): 
```

# 2. Expected behavior

# 3. Steps to reproduce

# 4. Flutter doctor output

```terminal
Output of: flutter doctor -v
```

# 5. More environment information

# 6. Log information

```terminal
Enter log information in this code block
```

# 7. More information

**Comment by myConsciousness** [comment]
This is not the supported parameter.

```json
{
    "errors": [
        {
            "parameters": {
                "expansions": [
                    "\"author_id,in_reply_to_user_id\""
                ]
            },
            "message": "The field in the request body [expansions] is not one of [for_super_followers_only,poll,reply_settings,geo,text,reply,quote_tweet_id,direct_message_deep_link,media]"
        }
    ],
    "title": "Invalid Request",
    "detail": "One or more parameters to your request was invalid.",
    "type": "https://api.twitter.com/2/problems/invalid-request"
}
```

**Comment by myConsciousness** [comment]
Also:

```dart
{
    "errors": [
        {
            "parameters": {
                "place.fields": [],
                "expansions": [
                    "author_id,in_reply_to_user_id"
                ],
                "tweet.fields": [],
                "poll.fields": [],
                "user.fields": [],
                "media.fields": []
            },
            "message": "None of [expansions, tweet.fields, media.fields, poll.fields, place.fields, user.fields] may be provided."
        }
    ],
    "title": "Invalid Request",
    "detail": "One or more parameters to your request was invalid.",
    "type": "https://api.twitter.com/2/problems/invalid-request"
}
```
