### ISSUE TITLE
Control when data or meta is unexpectedly null

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#41]
# 1. What could be improved

Some tweets existed at a certain moment, but during the processing, the author of the tweet deletes the tweet to be processed, so there are cases in which data cannot be obtained exceptionally. Therefore, we will consider whether these exceptional results can be covered as a TwitterException.

# 2. Why should this be improved

# 3. Any risks?

# 4. More information

**Comment by myConsciousness** [comment]
Make it object.

```dart
{
   "errors":[
      {
         "message":"This tweet cannot be found."
      }
   ],
   "title":"Invalid Request",
   "detail":"One or more parameters to your request was invalid.",
   "type":"https://api.twitter.com/2/problems/invalid-request"
}
```

**Comment by myConsciousness** [comment]
Also, when we try to search a not exist word.

```bash
Unhandled exception:
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<TweetData>(Closure: (dynamic) => TweetData)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _TweetsService.searchRecent (package:twitter_api_v2/src/service/tweets/tweets_service.dart:670:12)
<asynchronous suspension>
#2      main (file:///Users/katoushinya/twitter-api-v2/example/example.dart:31:22)
<asynchronous suspension>
```

**Comment by myConsciousness** [comment]
> Make it object.
> 
> ```json
> {
>    "errors":[
>       {
>          "message":"This tweet cannot be found."
>       }
>    ],
>    "title":"Invalid Request",
>    "detail":"One or more parameters to your request was invalid.",
>    "type":"https://api.twitter.com/2/problems/invalid-request"
> }
> ```

This should be split into a separate issue.
