### ISSUE TITLE
Could not create `_$_TweetData`. There is a problem with "lang". `qme` is not one of the supported values:

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#570]
# 1. Current bug behavior

```bash
Unhandled exception:
CheckedFromJsonException
Could not create `_$_TweetData`.
There is a problem with "lang".
`qme` is not one of the supported values: am, de, ml, sk, ar, el, dv, sl, hy, gu, mr, ckb, eu, ht, ne, es, bn, iw, no, sv, bs, hi, or, tl, bg, hi-Latn, pa, ta, my, hu, ps, te, hr, is, fa, th, ca, in, pl, bo, cs, it, pt, zh, zh-TW, da, ja, ro, tr, nl, kn, ru, uk, en, km, sr, ur, et, ko, zh-CN, ug, fi, lo, sd, vi, fr, lv, si, cy, ka, lt, und
#0      $checkedConvert (package:json_annotation/src/checked_helpers.dart:92:5)
#1      $checkedCreate.checkedConvert (package:json_annotation/src/checked_helpers.dart:29:7)
#2      _$$_TweetDataFromJson.<anonymous closure> (package:twitter_api_v2/src/service/tweets/tweet_data.g.dart:76:32)
#3      $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:34:22)
#4      $checkedNew (package:json_annotation/src/checked_helpers.dart:52:23)
#5      $checkedCreate (package:json_annotation/src/checked_helpers.dart:31:10)
#6      _$$_TweetDataFromJson (package:twitter_api_v2/src/service/tweets/tweet_data.g.dart:11:49)
#7      new _$_TweetData.fromJson (package:twitter_api_v2/src/service/tweets/tweet_data.freezed.dart:739:7)
#8      _$TweetDataFromJson (package:twitter_api_v2/src/service/tweets/tweet_data.freezed.dart:18:21)
#9      new TweetData.fromJson (package:twitter_api_v2/src/service/tweets/tweet_data.dart:280:7)
#10     _$$_IncludesFromJson.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:twitter_api_v2/src/service/common/includes.g.dart:20:33)
```

# 2. Expected behavior

# 3. Steps to reproduce

# 4. Flutter doctor output

```terminal
Output of: flutter doctor -v
```

# 5. More environment information

# 6. Log information

```terminal
Enter log information in this code block
```

# 7. More information

**Comment by myConsciousness** [comment]
Such a model with Enum as the type might be better implemented in a safer way.

For example, in this case, `undefined` should be set even if the code comes in unsupported.

**Comment by myConsciousness** [comment]
However, the problem with the above method is that when the response data is serialized/deserialized, it's no longer compatible with the original data. 

Given this, it would be better to simply add the missing code.

**Comment by myConsciousness** [comment]
https://twittercommunity.com/t/unkown-language-code-qht-returned-by-api/172819

**Comment by myConsciousness** [comment]
[lang:qam](https://twitter.com/search?q=lang%3Aqam&src=typed_query&f=live) for tweets with mentions only (works for tweets since 2022-06-14)
[lang:qct](https://twitter.com/search?q=lang%3Aqct&src=typed_query&f=live) for tweets with cashtags only (works for tweets since 2022-06-14)
[lang:qht](https://twitter.com/search?q=lang%3Aqht&src=typed_query&f=live) for tweets with hashtags only (works for tweets since 2022-06-14)
[lang:qme](https://twitter.com/search?q=lang%3Aqme&src=typed_query&f=live) for tweets with media links (works for tweets since 2022-06-14)
[lang:qst](https://twitter.com/search?q=lang%3Aqst&src=typed_query&f=live) for tweets with a very short text (works for tweets since 2022-06-14)
[lang:zxx](https://twitter.com/search?q=lang%3Azxx&src=typed_query&f=live) for tweets with either media or Twitter Card only, without any additional text (works for tweets since 2022-06-14)
